name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - refactor-ci

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ matrix.stack }}
    strategy:
      matrix:
        stack: [iam, budgets, certificates, route-53, bertie-blackman]
    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Check Out Repository
        uses: 'actions/checkout@v2'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: NPM Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Deploy ${{ matrix.stack }}
        run: npm run deploy ${{ matrix.stack }}

      # - name: Deploy budgets
      #   run: npm run deploy budgets

      # - name: Deploy certificates
      #   run: npm run deploy certificates

      # - name: Deploy route-53
      #   run: npm run deploy route-53

      # - name: Deploy bertie-blackman
      #   run: npm run deploy bertie-blackman

      # - name: Deploy bertie-blackman-ses
      #   env:
      #     AWS_DEFAULT_REGION: us-east-1
      #   run: |
      #     npm run deploy bertie-blackman-ses
      #     aws ses set-active-receipt-rule-set --rule-set-name 'bertie-blackman-ses-rule-set'
