name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    name: Quality Checks

    steps:
      - name: Check Out Repository
        uses: 'actions/checkout@v2'

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: NPM Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Check Formatting
        run: yarn prettier:check

      - name: Lint
        run: yarn lint:check

      - name: Type Check
        run: yarn build

      - name: Unit Test
        run: yarn test

  deploy-stacks-cdk:
    runs-on: ubuntu-latest
    name: Deploy Stack '${{ matrix.stack }}' via CDK
    needs: [quality-checks]

    strategy:
      matrix:
        stack: [iam, budgets, certificates, bertie-blackman, bertie-blackman-ses, ec2]
    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Check Out Repository
        uses: 'actions/checkout@v2'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: NPM Install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Deploy ${{ matrix.stack }}
        run: yarn deploy ${{ matrix.stack }}

  deploy-aws-cli:
    runs-on: ubuntu-latest
    name: Deploy via CLI
    needs: [quality-checks]

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy bertie-blackman-ses
        run: |
          aws ses set-active-receipt-rule-set --rule-set-name 'bertie-blackman-ses-rule-set'
