name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-16.04
    name: Deploy Stacks
    env:
      AWS_REGION: eu-west-2

    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Restore node_modules
        id: cache-node-modules
        uses: actions/cache@master
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: NPM install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Deploy IAMStack
        run: npm run deploy IAMStack

      - name: Deploy BudgetsStack
        run: npm run deploy BudgetsStack
